#!/bin/bash

ssh_setup() {
    _SheliacCore_fModuleDesc="Conn"
}

ssh_canConnect() {
    server="$1"
    port="$2"
    ssh $server "printf 'test\n'" > /dev/null 2>&1
    if [ "$?" = "0" ]
    then
        Sheliac_fRetval=$(true)
        return 0
    elif [ "$?" != "0" ]
    then
        ssh "${server}":"${port}" "printf 'test\n'" > /dev/null 2>&1 && Sheliac_fRetval=$(true) || Sheliac_fRetval=$(false)
        return 1
    fi
}

ssh_connect() {
    server="$1"
    port="$2"
    ssh_canConnect "$server" "$port"
    if [ "$?" = "0" ]
    then
        Sheliac_fRetval="ssh -t ${server} --"
    else
        Sheliac_fRetval="ssh -t ${server}:${port} --"
    fi
}

ssh_configure() {
    server="$1"
    port="$2"
    config_location="$3"
    placement_location="$4"
    ssh_canConnect "$server" "$port"
    if [ "$?" = "0" ]
    then
        Sheliac_fRetval="cat ${configure_location} | ssh ${server} \"cat > ${placement_location}\""
    else
        Sheliac_fRetval="cat ${configure_location} | ssh ${server}:${port} \"cat > ${placement_location}\""
    fi
}
