#!/bin/sh

apt_install(){
    server="$1"
    pack="$2"
    Sheliac_pRetval="${server} apt-get install ${pack}"
}

apt_remove(){
    pack="$1"
    Sheliac_pRetval="${server} apt-get remove ${pack}"
}

apt_update(){
    pack="$1"
    Sheliac_pRetval="${server} apt-get upgrade ${pack}"
}

apt_setup(){
    Sheliac_pRetval=$(true)
}

apt_canrun(){
    Sheliac_pRetval=$(true)
}
