#!/bin/sh

_apt_elevation_program="sudo"
_apt_elevation_program="su -c"
apt_install(){
    server="$1"
    pack="$2"
    Sheliac_pRetval="${server} \"${_apt_elevation_program} 'apt-get -y install ${pack}'\""
}

apt_remove(){
    server="$1"
    pack="$2"
    Sheliac_pRetval="${server} \"${_apt_elevation_program} 'apt-get -y remove ${pack}'\""
}

apt_update(){
    server="$1"
    pack="$2"
    Sheliac_pRetval="${server} \"${_apt_elevation_program} 'apt-get -y upgrade ${pack}'\""
}

apt_setup(){
    Sheliac_pRetval=0
}

apt_canRun(){
    server="$1"
    _rval=0
    $(eval "${server} 'apt -h > /dev/null 2>&1 && apt-get -h > /dev/null 2>&1'") || _rval="${?}"
    if [ "${_rval}" = "0" ]
    then
        Sheliac_pRetval=0
    else
        Sheliac_pRetval=1
    fi
}
